[package]
name = "auth-api"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3" }
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["typed-header"] }
headers = "0.4.1"
hex = "0.4.3"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "net", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
